chore: fix type tests
Type tests were failing because of an irrelevant different ordering.
For example:
Error: /ptokens.js/packages/ptokens-prvn/types/tests/ptokens-prvn-test.ts:12:1
ERROR: 12:1  expect  Expected type to be:
  PromiEvent<string | TransactionReceipt | Report | RavencoinTransactionReceipt | RedeemResult>
got:
  PromiEvent<string | Report | TransactionReceipt | RavencoinTransactionReceipt | RedeemResult>